package com.opsbli.demo.dto;


import com.opsbli.demo.domain.UserEntity;
import lombok.Data;
import com.easy.query.core.annotation.Column;

/**
 * this file automatically generated by easy-query struct dto mapping
 * 当前文件是easy-query自动生成的 结构化dto 映射
 * {@link UserEntity }
 *
 * @author easy-query
 */
@Data
public class UserEntityDTO {


    @Column(value = "id")
    private Integer id;
    private String name;
    private Integer balance;
    private Boolean enabled;
    private Integer companyId;


}
